export const mansProducts = (() => ({
  products: [
    {
      //1
      id: "207fb65a-ba6d-4e72-a54e-fb9c7bce8863",
      brand: "InnoNex Solutions",
      model: "PulseTech Precision Runners",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, ipsum.",
      features: ["Lorem ipsum dolor sit amet."],
      price: 25.9,
      initialPrice: 33.9,
      rating: {reviews: 1, value: 2},
      stock: [
        {size: "40", count: 3},
        {size: "40.5", count: 1},
        {size: "41", count: 20},
        {size: "41.5", count: 9},
        {size: "42", count: 43},
        {size: "42.5", count: 16},
        {size: "43", count: 21},
        {size: "43.5", count: 22},
        {size: "44", count: 16},
        {size: "44.5", count: 9},
        {size: "45", count: 8},
        {size: "45.5", count: 0},
        {size: "46", count: 2},
        {size: "47", count: 1},
        {size: "48", count: 0},
        {size: "49", count: 0},
        {size: "50", count: 0},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/313be351-7e1b-4dbd-a430-0bc4fe380351/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/313be351-7e1b-4dbd-a430-0bc4fe380351/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/98a86196-75cd-4b7c-a1ee-9bbda1c2719e/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/146f5594-c188-470c-a095-3c2723eec8cf/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/489ab7a9-9a04-4d72-9e88-74148281a444/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/70ae285e-2160-4405-b758-8afe19a64218/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5690cd0e-cb27-4c7d-a5b9-95b543ab1f26/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5feb8dd2-1262-48c6-a12c-79631faff35b/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/43f4c0d9-5841-40d1-8113-94acac1df37e/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7267a6b6-2fd3-45c6-ac6f-3ed73b33b12e/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b8bda2f8-d313-48e1-80aa-a746ba2c3000/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ce03fd0f-e125-4adc-bd3d-05bb90747fe8/meskie-wodoszczelne-buty-do-biegania-w-terenie-pegasus-trail-4-gore-tex-tVWltb.png",
      ],
    },
    {
      //2
      id: "0e3a405d-80bd-4f2f-ad48-fe51dea707c5",
      brand: "QuantumSynth Innovations",
      model: "NovaNestle",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, dicta!",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores velit consectetur hic delectus tenetur atque libero quo sequi nostrum et.",
      features: ["Lorem ipsum dolor sit amet.", "Lorem ipsum dolor sit amet."],
      price: 45,
      initialPrice: 50,
      rating: {reviews: 7, value: 4.7},
      stock: [
        {size: "41", count: 2},
        {size: "41.5", count: 0},
        {size: "42", count: 0},
        {size: "42.5", count: 0},
        {size: "43", count: 0},
        {size: "43.5", count: 0},
        {size: "44", count: 3},
        {size: "44.5", count: 9},
        {size: "45", count: 8},
        {size: "45.5", count: 3},
        {size: "46", count: 5},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9022903b-ed99-4f2d-a441-58eb7c19a66c/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9022903b-ed99-4f2d-a441-58eb7c19a66c/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d56f140c-299b-46ad-b6aa-982de7831d6f/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/dcd90dfc-6f0c-4804-b39d-92a30f7e8767/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0259db8a-660f-421e-b24f-604621359be4/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0255f870-287e-4c3d-84bc-1c0aaaa1273b/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/82a41a33-c87b-4165-b1be-3ae6f0795d6f/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/14fbc366-22e1-4643-aa2c-c792a19cad62/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4313af88-f6e4-438c-b5fb-afb16a408728/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d4ae242b-589e-4318-a1fb-5f87b5afdd93/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2a8ae986-0537-4246-b11a-d99ee7dc088d/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-pegasus-39-shield-NSzMpm.png",
      ],
    },
    {
      //3
      id: "a554e792-619b-45f7-a18b-a05d5b03ed3b",
      brand: "QuantumSynth Innovations",
      model: "CelestialCraze",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur labore velit quidem!",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, similique enim id eos quidem numquam tempora eaque ut dignissimos saepe repellendus asperiores libero odit maxime, sed eligendi. Suscipit labore, distinctio animi architecto consequuntur deserunt fugiat enim odio. Iste, odio sit!",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
      ],
      price: 60,
      initialPrice: 60,
      rating: {reviews: 4, value: 3.66},
      stock: [
        {size: "41", count: 1},
        {size: "41.5", count: 16},
        {size: "42", count: 16},
        {size: "42.5", count: 22},
        {size: "43", count: 23},
        {size: "43.5", count: 26},
        {size: "44", count: 33},
        {size: "44.5", count: 16},
        {size: "45", count: 6},
        {size: "45.5", count: 3},
        {size: "46", count: 2},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4c41bcec-f8e9-4eaf-913d-e5fef6438749/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4c41bcec-f8e9-4eaf-913d-e5fef6438749/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/602fa2ec-04cc-41e1-adcf-357a64cc2864/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f656a59e-78e5-46fb-b231-ee14db9e6a8d/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/04d6f586-0a6f-4029-83a8-bdb23b3d55c6/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b744f780-d44c-4be6-b36e-960548db8919/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9f6c204a-33cf-4958-bc11-f09a7968dcc0/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c7ee6356-39f9-48af-8534-9c521735c749/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4531245c-52a1-44b7-ade7-63274313dbb8/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4c07844a-c8b6-4e45-982b-335a43e62838/meskie-buty-do-biegania-po-asfalcie-invincible-3-Mf9wcf.png",
      ],
    },
    {
      //4
      id: "54746076-e7e5-4a42-ad15-6fef055680bf",
      brand: "QuantumSynth Innovations",
      model: "EchoElegance",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem recusandae tenetur neque architecto pariatur.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, dolore nesciunt molestiae laudantium eum unde corrupti perferendis illum ratione nostrum assumenda, incidunt nemo veniam ipsum rem eligendi ad possimus soluta impedit odio ipsam aliquid. Incidunt, at sit aut asperiores laudantium accusamus iure maxime molestiae sunt deleniti optio sed amet pariatur.",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      ],
      price: 100,
      initialPrice: 111,
      rating: {reviews: 4, value: 3.1},
      stock: [
        {size: "41", count: 1},
        {size: "41.5", count: 16},
        {size: "42", count: 16},
        {size: "42.5", count: 22},
        {size: "43", count: 23},
        {size: "43.5", count: 26},
        {size: "44", count: 33},
        {size: "44.5", count: 16},
        {size: "45", count: 6},
        {size: "45.5", count: 3},
        {size: "46", count: 2},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c97f2721-3a96-432b-8e1b-ad9b2f304337/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c97f2721-3a96-432b-8e1b-ad9b2f304337/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/49500177-3565-4f5a-8aae-ac8302ed3ee9/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a29dcb8f-c0f2-40f0-aeb6-736121b14631/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7e2e558f-d60a-4b1d-8db2-8a3b67598d9b/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a2546c22-21f6-4f6e-928f-81f858b0ca71/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/176f611b-54be-469b-8a06-c1ab8f779c52/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/11400c22-0a67-45e0-a277-658236417fcc/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9d8a7912-977e-48fe-adff-f8b489de890e/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/711142e4-c784-4290-8c81-c9bab0f6b607/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a71463d6-d661-4d65-ab48-f41c46465a7d/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1f5f2bc8-b063-4584-8c43-7ade6281179d/meskie-wodoszczelne-buty-do-biegania-po-asfalcie-infinityrn-4-gore-tex-BcdT0P.png",
      ],
    },
    {
      //5
      id: "af7da8b7-d7c5-446e-9cd9-c6a0262ca841",
      brand: "SoleSynergy",
      model: "BlazeBrio",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat provident fugit sint, incidunt earum et veritatis?",
      description:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid cupiditate qui unde corrupti et quasi laborum officiis vitae odio molestias necessitatibus voluptate impedit adipisci tenetur consequuntur a, at deleniti dolores quae aperiam commodi in recusandae vel nam. Adipisci veniam odio earum natus? Asperiores molestiae repellat debitis nulla cupiditate sit dolorem.",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      ],
      price: 122,
      initialPrice: 133,
      rating: {reviews: 0, value: 0},
      stock: [
        {size: "40", count: 3},
        {size: "40.5", count: 1},
        {size: "41", count: 20},
        {size: "41.5", count: 9},
        {size: "42", count: 43},
        {size: "42.5", count: 16},
        {size: "43", count: 21},
        {size: "43.5", count: 22},
        {size: "44", count: 16},
        {size: "44.5", count: 9},
        {size: "45", count: 8},
        {size: "45.5", count: 0},
        {size: "46", count: 2},
        {size: "47", count: 1},
        {size: "48", count: 0},
        {size: "49", count: 0},
        {size: "50", count: 0},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9a7df257-f056-41e2-9af8-f9e397a1bf1d/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9a7df257-f056-41e2-9af8-f9e397a1bf1d/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3a72d646-c710-40e2-90d9-254e28164689/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/717fc616-1a4f-439d-8850-e1ec877094e8/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/47a0cf1d-8ce0-4116-bf70-acf6069bd543/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d29b0d8d-3873-48e3-bdb9-5423f68ab51e/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6488f03b-9ad2-440c-ad36-1b40eaa6992d/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7aa56ae4-9035-4108-a706-ea8b1b17fcf6/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c0bd0b81-efd5-4810-9335-2538627176bf/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/930edcae-7e75-42a3-ac0d-0cb3e056195e/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6826eda5-c3c3-4daa-8e2b-2a52b641049d/meskie-buty-do-biegania-po-asfalcie-w-kazdych-warunkach-pogodowych-wio-9-shield-BZVvzW.png",
      ],
    },
    {
      //6
      id: "50feb22e-2a53-4980-b52b-facf71a4b48c",
      brand: "SoleSynergy",
      model: "EtherealEclipse",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam eligendi ipsum perferendis. Recusandae debitis rem eos voluptate sequi!",
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa tempore quas ratione totam veritatis eum deleniti expedita minima laboriosam nam, quae sed aliquid reiciendis cum non nihil sunt neque iure. Ipsa eveniet ducimus expedita, quis ab magnam corrupti labore architecto dolores culpa nihil doloribus, illum ad rerum, vero ipsam illo! Tenetur iure vero iusto molestias fuga deleniti qui natus! At.",

      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      ],
      price: 144,
      initialPrice: 155,
      rating: {reviews: 3, value: 2.66},
      stock: [
        {size: "40", count: 3},
        {size: "40.5", count: 1},
        {size: "41", count: 20},
        {size: "41.5", count: 9},
        {size: "42", count: 43},
        {size: "42.5", count: 16},
        {size: "43", count: 21},
        {size: "43.5", count: 22},
        {size: "44", count: 16},
        {size: "44.5", count: 9},
        {size: "45", count: 8},
        {size: "45.5", count: 0},
        {size: "46", count: 2},
        {size: "47", count: 1},
        {size: "48", count: 0},
        {size: "49", count: 0},
        {size: "50", count: 0},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d975cae3-9659-43a1-b330-84cec15a9955/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d975cae3-9659-43a1-b330-84cec15a9955/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/cf987e9c-02ce-423f-b72e-0a55bb895506/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a8c69c5f-bd00-4156-82f5-686d7644ef92/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0904f3dc-e88f-4717-b8ad-ce9260370f3f/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/43e32596-28b8-4e05-8349-13aaa2bc5118/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8a16c163-e830-4011-9f47-877e2867cab3/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c44b7ef9-744d-48e1-9b69-d473a15eab3d/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/10f4d435-6327-48f0-9872-7d74fef2c795/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/073a1553-bb37-44ec-bf69-f2624f6ec05b/meskie-buty-do-biegania-po-asfalcie-pegasus-40-M88nP6.png",
      ],
    },
    {
      //7
      id: "80338793-8dbf-44cc-ac72-1b649880b457",
      brand: "SoleSynergy",
      model: "MirageMomentum",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus dolorem dolores dignissimos odio quas illum laudantium. Hic, soluta.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, est illum quod, enim impedit ea dolores nam doloremque provident amet laborum ab placeat iste fugit minima quia aliquam. Est ex cumque corporis quidem. Placeat voluptate dicta dolorum sequi labore maiores fugit ducimus accusamus omnis. Sequi, blanditiis quos voluptas consequuntur, minus voluptatem, vel magnam nisi fugit eaque quia adipisci maiores ut suscipit. Ex, alias optio. Architecto rerum officiis minus aperiam ad?",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      ],
      price: 145,
      initialPrice: 177,
      rating: {reviews: 1, value: 4},
      stock: [
        {size: "40", count: 3},
        {size: "40.5", count: 1},
        {size: "41", count: 20},
        {size: "41.5", count: 9},
        {size: "42", count: 43},
        {size: "42.5", count: 16},
        {size: "43", count: 21},
        {size: "43.5", count: 22},
        {size: "44", count: 16},
        {size: "44.5", count: 9},
        {size: "45", count: 8},
        {size: "45.5", count: 0},
        {size: "46", count: 2},
        {size: "47", count: 1},
        {size: "48", count: 0},
        {size: "49", count: 0},
        {size: "50", count: 0},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/04f94fdb-c5c0-4956-83dd-d61cab63e267/meskie-buty-do-biegania-po-asfalcie-infinityrn-4-GM5ls9.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/04f94fdb-c5c0-4956-83dd-d61cab63e267/meskie-buty-do-biegania-po-asfalcie-infinityrn-4-GM5ls9.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/867e0329-7f50-4744-9d4a-bde3c0cc2c39/meskie-buty-do-biegania-po-asfalcie-infinityrn-4-GM5ls9.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/10fb34e3-6869-4bdc-877a-251d4893ed97/meskie-buty-do-biegania-po-asfalcie-infinityrn-4-GM5ls9.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4c9b999c-e19b-454e-8bd1-1851ef187559/meskie-buty-do-biegania-po-asfalcie-infinityrn-4-GM5ls9.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a5741b2c-aba1-4271-86c6-1b1540f5fcd3/meskie-buty-do-biegania-po-asfalcie-infinityrn-4-GM5ls9.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5afde1cd-4bf0-457c-9bef-3688932807a4/meskie-buty-do-biegania-po-asfalcie-infinityrn-4-GM5ls9.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a8e1f0f1-2223-4a27-bb10-af30813f7434/meskie-buty-do-biegania-po-asfalcie-infinityrn-4-GM5ls9.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fb330b30-d53d-4aab-a5a0-c98665e5460a/meskie-buty-do-biegania-po-asfalcie-infinityrn-4-GM5ls9.png",
      ],
    },
    {
      //8
      id: "0d69f963-7ec4-4494-a0e8-64a845dfaaff",
      brand: "EphemeralEleganceFootwearEmporium",
      model: "SereneSpectra",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt quasi nulla recusandae doloribus facilis doloremque similique, quam reprehenderit.",
      description:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Distinctio laboriosam pariatur recusandae quo ex fuga in itaque quasi quis earum fugiat inventore cumque, vel totam ea eos quibusdam dignissimos. Cumque debitis earum assumenda voluptatum, dolorum animi et, optio vero quibusdam totam id. Eos et quidem saepe corporis optio! Eius voluptates autem quisquam doloribus nostrum! Aut sit facere repellendus quaerat incidunt architecto vel corrupti temporibus blanditiis, quia odit perferendis culpa optio! Rem, veritatis veniam pariatur harum est vero ullam earum. Distinctio!",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      ],
      price: 150.01,
      initialPrice: 201.06,
      rating: {reviews: 2, value: 4.5},
      stock: [
        {size: "41", count: 0},
        {size: "42", count: 0},
        {size: "43", count: 0},
        {size: "44", count: 0},
        {size: "45", count: 0},
        {size: "46", count: 0},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/477abbf8-b37a-4fe6-b516-08e294a8487a/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/477abbf8-b37a-4fe6-b516-08e294a8487a/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5091858d-4ed7-44d8-8160-a7fba4720f32/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/87f531e0-13d1-46d0-b60c-e2c628adec7c/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8a3f948d-bd33-459a-b8dd-57dbe9b809ca/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e1a7071f-6722-4e00-b03a-1d08e27d5a32/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e2de2bc7-801c-44e9-84a9-215bdfee7e01/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8cd0efee-c124-4544-9ece-edf0b69de928/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/33bc5f47-58fb-47ae-bb0a-319bea5e5ff0/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/af6f0e06-259b-4b15-8796-252e9d7b4f85/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d16590af-ed48-41fc-8873-89904595102b/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b57a9a49-b288-4600-8dd5-4098547b57fa/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/793adada-eb18-4f6f-8a0f-b60147b76ab3/meskie-buty-startowe-do-biegania-po-asfalcie-alphafly-3-B9kfmF.png",
      ],
    },
    {
      //9
      id: "42d7498f-765a-4996-acea-bfc3d19421a6",
      brand: "EphemeralEleganceFootwearEmporium",
      model: "QuantumQuillbyEphemeralEleganceFootwearEmporium",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolores laboriosam blanditiis officiis vero rem ipsa aspernatur eum id deserunt dolorem!",
      description:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt, itaque ex autem est dolorum necessitatibus illo aut alias, animi sunt minus delectus eligendi sit aliquam suscipit. Sunt, quos expedita? Velit reiciendis rem eveniet soluta officiis recusandae nemo totam officia nostrum odio. Recusandae, quos beatae eum molestiae corporis earum officia velit alias explicabo repudiandae atque. Accusamus soluta amet, repudiandae consequatur praesentium optio doloribus repellendus illo eius nemo minus ex laborum. Culpa non hic numquam reprehenderit dignissimos ratione? Quibusdam laborum officia neque earum molestiae?",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
      ],
      price: 180.19,
      initialPrice: 201.21,
      rating: {reviews: 1, value: 3},
      stock: [
        {size: "41", count: 15},
        {size: "42", count: 19},
        {size: "43", count: 0},
        {size: "44", count: 11},
        {size: "45", count: 1},
        {size: "46", count: 1},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a3973ff2-3669-47c5-9ee4-849ca4afd403/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a3973ff2-3669-47c5-9ee4-849ca4afd403/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/418250d9-695f-4c6f-b44b-030bdde6b62c/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f8891f15-da66-464a-b5b5-3cb57c1cca86/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/774ce636-56ef-4b15-8fc3-a75aa52db413/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/cbd41fca-9f9f-4aae-a7db-923fcc8d5b9f/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9dfaed9a-33c4-46fb-a64c-438deb8ac69c/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a4bf3832-6db7-4edb-95d8-37691a6877a4/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2770edae-4d23-4fac-93e1-450acb5dced1/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5a05e554-ba3c-41ed-8221-d1b9070882b3/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ba90c173-5242-406f-ae7d-bf478e7ecd21/meskie-buty-startowe-do-biegania-po-asfalcie-vaporfly-3-JN8h5q.png",
      ],
    },
    {
      //10
      id: "8a063df7-3222-4c73-b1a3-c420242b899c",
      brand: "EphemeralEleganceFootwearEmporium",
      model: "NebulaNectar",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Placeat enim, id, nobis nam non odio, recusandae eos alias quae incidunt fugit laboriosam!",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum iste laborum ipsum repellendus dolorem vero fugiat, tempora laudantium quaerat magni perferendis cupiditate, magnam minima possimus voluptate corporis rerum aspernatur doloribus, dicta impedit consectetur. Praesentium obcaecati excepturi itaque explicabo deserunt similique cum, sint quo vel, alias labore perspiciatis ducimus mollitia. Quibusdam doloremque deleniti tempore, omnis cumque distinctio reiciendis. Cupiditate animi necessitatibus eius et unde tenetur obcaecati corrupti delectus nemo consequatur rem sunt, nam deserunt reiciendis, provident magnam voluptates velit? Mollitia blanditiis quisquam doloribus, ratione quam minima, aliquam distinctio, veniam at cum voluptas eaque sed sapiente debitis? Blanditiis iure deleniti consequatur magni.",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
      ],
      price: 57.03,
      initialPrice: 57.03,
      rating: {reviews: 0, value: 0},
      stock: [
        {size: "41", count: 16},
        {size: "42", count: 12},
        {size: "43", count: 15},
        {size: "44", count: 15},
        {size: "45", count: 15},
        {size: "46", count: 15},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e53419df-8536-4c14-8f0d-2e481b1fad2f/meskie-buty-do-biegania-po-asfalcie-downshifter-12-zhJr9p.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e53419df-8536-4c14-8f0d-2e481b1fad2f/meskie-buty-do-biegania-po-asfalcie-downshifter-12-zhJr9p.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/251341bc-2862-4f1d-8c8d-ec86e68363a7/meskie-buty-do-biegania-po-asfalcie-downshifter-12-zhJr9p.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d5c2a7cb-82e5-4871-bcbf-b5f5c88754f7/meskie-buty-do-biegania-po-asfalcie-downshifter-12-zhJr9p.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3a58103d-7cae-495f-a0df-cdbf3944af2f/meskie-buty-do-biegania-po-asfalcie-downshifter-12-zhJr9p.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/354a7fb3-28fb-4462-94b7-60ca9a812480/meskie-buty-do-biegania-po-asfalcie-downshifter-12-zhJr9p.png",
      ],
    },
    {
      //11
      id: "ec8b2eb6-b777-46d7-b85d-137ec94fe448",
      brand: "EphemeralEleganceFootwearEmporium",
      model: "VerveVortex",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum magnam quibusdam, sint magni veritatis dolorum officia voluptatem ipsa? Alias obcaecati officia natus temporibus!",
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quam perferendis totam molestias consequatur libero voluptatum nulla. Autem facilis hic quae tenetur? Nemo quisquam quidem perspiciatis nam cupiditate dolores culpa fugit facilis mollitia! Accusamus inventore culpa nihil. Qui consequatur, dolorem, nihil hic soluta neque nobis quae delectus aperiam ex atque, placeat quasi laboriosam quos ullam. Minima, provident! Explicabo vitae, ipsa, sint ut consequatur magni deleniti illo voluptatum quam, tempore aliquid libero facilis temporibus laudantium exercitationem enim est? Magnam, veritatis. Explicabo similique molestiae natus suscipit atque ducimus possimus ad earum eos dolore maxime, ullam optio cum, autem iste ipsum repudiandae porro debitis odio doloremque placeat, perspiciatis quam reiciendis. Eveniet quibusdam qui amet!",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
      ],
      price: 120.09,
      initialPrice: 120.09,
      rating: {reviews: 0, value: 0},
      stock: [
        {size: "41", count: 1},
        {size: "42", count: 16},
        {size: "43", count: 23},
        {size: "44", count: 33},
        {size: "45", count: 6},
        {size: "46", count: 2},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/02b794ab-1268-4018-9e11-e31670efbef1/meskie-buty-do-biegania-po-asfalcie-vomero-17-RsQ4DC.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/02b794ab-1268-4018-9e11-e31670efbef1/meskie-buty-do-biegania-po-asfalcie-vomero-17-RsQ4DC.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/02a79fff-c4b6-4d7d-ab2e-1c4b854a1ff9/meskie-buty-do-biegania-po-asfalcie-vomero-17-RsQ4DC.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9c684f0e-7642-4647-bb9c-dfc3120ed1b5/meskie-buty-do-biegania-po-asfalcie-vomero-17-RsQ4DC.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/bddd3888-2d88-4d0e-aa22-907c8551b89b/meskie-buty-do-biegania-po-asfalcie-vomero-17-RsQ4DC.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4a6f5702-a1e7-48a0-b56e-5799f1bb5919/meskie-buty-do-biegania-po-asfalcie-vomero-17-RsQ4DC.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4c8f9146-db21-4947-a5c6-0995d2fec43b/meskie-buty-do-biegania-po-asfalcie-vomero-17-RsQ4DC.png",
      ],
    },
    {
      //12
      id: "b6ed699f-a210-42ca-8276-cf8c90be76d5",
      brand: "Stride_Craft",
      model:
        "EchoEnigmabyStride_Craftmodel2000 long long long long long long long modelname",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum reiciendis sunt sapiente quia sequi possimus recusandae cupiditate totam, dolorem exercitationem! Autem minus dolore nobis provident quae!",
      description:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur quos temporibus id minus pariatur. Ducimus voluptates unde quidem! Nihil, deserunt. Debitis praesentium repellat aliquid? Labore, eum, animi saepe fugit iusto deleniti officia facilis neque doloremque placeat illum rerum mollitia ullam aut vero laboriosam! Placeat possimus cupiditate amet rem voluptatum mollitia incidunt aliquid ipsa pariatur debitis cumque, aperiam minus delectus consequatur dolore magni quis nisi reiciendis corrupti quam? Accusantium inventore, neque aut quo officiis, nisi, eos vel quod pariatur deserunt cumque excepturi atque maiores iste dolorum? Itaque, voluptas amet rem id officiis totam sit! Porro molestiae esse nobis. Voluptas quae, voluptates unde aut ea, eum impedit, facere nobis ipsam officia consectetur! Voluptatibus eius asperiores blanditiis, tempora eveniet excepturi eum harum minima?",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
      ],
      price: 15,
      initialPrice: 199,
      rating: {reviews: 3, value: 4.1},
      stock: [
        {size: "40", count: 0},
        {size: "40.5", count: 0},
        {size: "41", count: 1},
        {size: "41.5", count: 0},
        {size: "42", count: 1},
        {size: "42.5", count: 0},
        {size: "43", count: 1},
        {size: "43.5", count: 5},
        {size: "44", count: 1},
        {size: "44.5", count: 0},
        {size: "45", count: 0},
        {size: "45.5", count: 0},
        {size: "46", count: 2},
        {size: "47", count: 0},
        {size: "48", count: 0},
        {size: "49", count: 0},
        {size: "50", count: 0},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/17181039-eaff-4265-924a-c079e9a48878/meskie-buty-do-biegania-po-asfalcie-pegasus-40-QQ3rnn.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/17181039-eaff-4265-924a-c079e9a48878/meskie-buty-do-biegania-po-asfalcie-pegasus-40-QQ3rnn.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/061def31-1d34-43d5-a04b-380ccce315e7/meskie-buty-do-biegania-po-asfalcie-pegasus-40-QQ3rnn.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c9f949be-67fd-4baf-8c43-ce302f822b33/meskie-buty-do-biegania-po-asfalcie-pegasus-40-QQ3rnn.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/92ebc91e-daa2-46ec-8acb-f35dd16af5be/meskie-buty-do-biegania-po-asfalcie-pegasus-40-QQ3rnn.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/660477ef-667f-47ac-92ed-c04bb8655a4f/meskie-buty-do-biegania-po-asfalcie-pegasus-40-QQ3rnn.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/38ef7027-3b12-4387-bb06-09ac95cd81a3/meskie-buty-do-biegania-po-asfalcie-pegasus-40-QQ3rnn.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ce32631f-3613-4b61-9db8-8d12dd0855e4/meskie-buty-do-biegania-po-asfalcie-pegasus-40-QQ3rnn.png",
      ],
    },
    {
      //13
      id: "fca0afb8-30ab-4529-87c3-6a4d9481b97c",
      brand: "Stride_Craft",
      model: "ZenithZephyr",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id cupiditate recusandae nostrum eius voluptates vero, necessitatibus odit? Accusamus, reprehenderit. Hic veritatis voluptatum laudantium eveniet! Soluta voluptatibus enim cumque!",
      description:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat at, unde molestiae vel, magnam omnis sed saepe dolore praesentium nostrum tempora? Atque, in eos? Asperiores ut inventore voluptate. Odit tempore debitis aut quia unde non a nostrum asperiores rem nisi dignissimos laboriosam maiores necessitatibus vel ullam voluptatibus ut possimus fugit eum corporis, placeat enim natus! Eum, exercitationem ratione. Officia quod dignissimos autem? Quae nobis iste iusto, aliquam sequi recusandae repudiandae aut ipsum consequatur! Nihil iure sapiente quidem, voluptatibus animi voluptatem est! Quo magni quisquam officia quaerat ipsum, praesentium inventore, illum magnam corporis labore reprehenderit reiciendis non quia. Nam sed, velit quisquam quod nemo voluptas laudantium distinctio, omnis in sunt dolore libero, alias laborum. Ipsam blanditiis consequatur voluptatem ab perspiciatis corrupti repellat tenetur porro laboriosam! Temporibus culpa nostrum facilis neque repellat.",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
      ],
      price: 1500,
      initialPrice: 3000,
      rating: {reviews: 1, value: 2},
      stock: [
        {size: "40", count: 3},
        {size: "40.5", count: 1},
        {size: "41", count: 20},
        {size: "41.5", count: 9},
        {size: "42", count: 43},
        {size: "42.5", count: 16},
        {size: "43", count: 21},
        {size: "43.5", count: 22},
        {size: "44", count: 16},
        {size: "44.5", count: 9},
        {size: "45", count: 8},
        {size: "45.5", count: 0},
        {size: "46", count: 2},
        {size: "47", count: 1},
        {size: "48", count: 0},
        {size: "49", count: 0},
        {size: "50", count: 0},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/29a69268-55ec-4414-9dc9-061e17027a6b/meskie-buty-do-biegania-w-terenie-zegama-ZdbtbB.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/29a69268-55ec-4414-9dc9-061e17027a6b/meskie-buty-do-biegania-w-terenie-zegama-ZdbtbB.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4e35edf0-47ad-40f7-ba57-f5a3252799b1/meskie-buty-do-biegania-w-terenie-zegama-ZdbtbB.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c0093571-1211-4651-9efc-10deabb92051/meskie-buty-do-biegania-w-terenie-zegama-ZdbtbB.png",
      ],
    },
    {
      //14
      id: "fca0afb8-30ab-4529-87c3-6a4d9481b97c",
      brand: "Stride_Craft",
      model: "RadiantRover",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti consectetur voluptates qui, ratione facere labore adipisci hic amet error? Officia ad minus sapiente perspiciatis totam veniam consequuntur vel!",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, sint perferendis harum soluta culpa nesciunt sequi libero dolorum voluptatibus modi architecto doloremque ad dicta optio provident quod commodi, temporibus nihil. Dolore maxime, facilis quasi dolores ullam laudantium aspernatur nobis dicta ducimus velit sed, nesciunt placeat laborum optio minus similique vitae expedita iusto cumque rem perferendis qui accusamus iste molestiae? Tenetur incidunt excepturi at exercitationem vitae. Nobis corporis ipsa beatae dicta molestiae. Aperiam possimus consectetur, ex voluptates officiis amet facilis. Tempora autem repudiandae et sed voluptatem nostrum corrupti consequatur mollitia odio facere nisi error, architecto deserunt asperiores expedita est quas veniam harum porro impedit commodi fugiat? Et, unde id necessitatibus ipsa eius eaque, nobis rem maxime quis animi non harum aspernatur incidunt? Numquam libero recusandae debitis assumenda molestiae obcaecati explicabo distinctio, earum atque a quae quibusdam, dolores aspernatur. Impedit, vero nobis!",

      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
      ],
      price: 390,
      initialPrice: 999,
      rating: {reviews: 8, value: 4.63},
      stock: [
        {size: "40", count: 3},
        {size: "40.5", count: 1},
        {size: "41", count: 20},
        {size: "41.5", count: 9},
        {size: "42", count: 43},
        {size: "42.5", count: 16},
        {size: "43", count: 21},
        {size: "43.5", count: 22},
        {size: "44", count: 16},
        {size: "44.5", count: 9},
        {size: "45", count: 8},
        {size: "45.5", count: 0},
        {size: "46", count: 2},
        {size: "47", count: 1},
        {size: "48", count: 0},
        {size: "49", count: 0},
        {size: "50", count: 0},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f9d31118-d3fd-4336-bb85-a9fd8b1555fb/meskie-buty-do-biegania-po-asfalcie-renew-ride-3-prSl6s.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f9d31118-d3fd-4336-bb85-a9fd8b1555fb/meskie-buty-do-biegania-po-asfalcie-renew-ride-3-prSl6s.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0717d44e-67c2-4773-9723-c73160755f90/meskie-buty-do-biegania-po-asfalcie-renew-ride-3-prSl6s.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/de3f75bf-5e27-4fa3-b54a-7610044c5f74/meskie-buty-do-biegania-po-asfalcie-renew-ride-3-prSl6s.png",
      ],
    },
    {
      //15
      id: "fca0afb8-30ab-4529-87c3-6a4d9481b97c",
      brand: "PinnaclePeds",
      model: "LunarLux",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed pariatur iure maxime sit? Eius eos architecto et placeat dicta magni, sunt excepturi laborum velit aut, fugit debitis nemo quis amet!",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis voluptates repellendus tenetur ad numquam earum at temporibus ex fuga, impedit facilis quas amet. Saepe quod labore nihil odio repellendus ullam similique molestiae sapiente itaque corporis a, totam maxime adipisci distinctio illum! Dicta excepturi recusandae commodi suscipit et rerum, officiis tempore corrupti neque natus. Quis natus voluptas reiciendis tempore iure facilis totam delectus laborum. Eos optio commodi voluptatibus voluptates unde ad cum hic, assumenda natus dicta? Ratione consectetur rem sit. Odit quae amet quod voluptatibus debitis. Officia sunt, velit quaerat molestiae, reprehenderit neque nesciunt, quo veritatis quae aut necessitatibus impedit numquam incidunt aliquid esse quisquam voluptates fuga ex consectetur dolorem modi omnis iste minus? Odit hic omnis dolore, tempora ex eum, consectetur vitae, excepturi et corporis nisi eaque nihil. Nisi voluptatem quam doloremque incidunt enim. Cum animi asperiores repellat, eaque numquam quam porro velit minus beatae delectus provident repellendus. Dolorum, veniam.",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
      ],
      price: 155,
      initialPrice: 155,
      rating: {reviews: 2, value: 4.5},
      stock: [
        {size: "41", count: 1},
        {size: "42", count: 16},
        {size: "43", count: 23},
        {size: "44", count: 33},
        {size: "45", count: 6},
        {size: "46", count: 2},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a8a2601d-b580-4b1e-af69-22a0f16b67f7/meskie-buty-do-biegania-po-asfalcie-z-systemem-latwego-wkladania-i-zdejmowania-pegasus-flyease-sB8rnR.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a8a2601d-b580-4b1e-af69-22a0f16b67f7/meskie-buty-do-biegania-po-asfalcie-z-systemem-latwego-wkladania-i-zdejmowania-pegasus-flyease-sB8rnR.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5dfffaff-32b6-46dc-b6b1-ee032cc86d4d/meskie-buty-do-biegania-po-asfalcie-z-systemem-latwego-wkladania-i-zdejmowania-pegasus-flyease-sB8rnR.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/707f2283-b7a4-44c7-a242-5e29ab60a7a3/meskie-buty-do-biegania-po-asfalcie-z-systemem-latwego-wkladania-i-zdejmowania-pegasus-flyease-sB8rnR.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f6f03456-6f4b-4e45-97b5-423886d27d14/meskie-buty-do-biegania-po-asfalcie-z-systemem-latwego-wkladania-i-zdejmowania-pegasus-flyease-sB8rnR.png",
      ],
    },
    {
      //16
      id: "fca0afb8-30ab-4529-87c3-6a4d9481b97c",
      brand: "PinnaclePeds",
      model: "VelocityVista 9000",
      category: "sneaker-shoes",
      shortDescription:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque autem quam corporis laborum suscipit cumque libero aut eos nemo reprehenderit architecto earum, dicta, commodi illum dignissimos animi illo praesentium veniam sint? Distinctio?",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. In dicta non ipsum sed, totam reprehenderit deleniti! Nemo atque natus possimus saepe alias? Consequuntur ullam quia voluptatem repellendus ratione illum vel amet iure quos minima. Optio vero reprehenderit distinctio aperiam consectetur esse, explicabo dolor veniam officiis dicta placeat modi ut laudantium rerum eius doloremque rem saepe a. Voluptatum beatae itaque necessitatibus autem ratione dicta ut veritatis recusandae vel, placeat quasi. Rerum facilis aliquam commodi dicta nesciunt autem ipsa voluptatibus pariatur expedita quasi, sint vitae ea. Odio atque libero asperiores facere fugiat possimus veniam enim quo at qui delectus, ipsa sit corporis. Voluptate, facere maiores ipsum excepturi nisi voluptatem sunt sapiente? Eveniet delectus aut voluptatem, ullam error dolorum nihil nesciunt neque ipsam fuga omnis est doloribus ex nisi exercitationem adipisci praesentium illo consequuntur autem tempora similique, vitae accusamus, sit sed? Blanditiis distinctio asperiores voluptatum quo impedit, iste doloremque accusantium esse facere repellendus voluptatem hic est dolorem debitis quasi. Eos dignissimos eius perspiciatis!",
      features: [
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident maiores, perspiciatis asperiores quisquam officiis cum sint deserunt",
      ],
      price: 222,
      initialPrice: 256,
      rating: {reviews: 3, value: 3.76},
      stock: [
        {size: "41", count: 1},
        {size: "42", count: 16},
        {size: "43", count: 23},
        {size: "44", count: 33},
        {size: "45", count: 6},
        {size: "46", count: 2},
      ],
      thumbnail:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c0093571-1211-4651-9efc-10deabb92051/meskie-buty-do-biegania-w-terenie-zegama-ZdbtbB.png",
      images: [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c0093571-1211-4651-9efc-10deabb92051/meskie-buty-do-biegania-w-terenie-zegama-ZdbtbB.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4e35edf0-47ad-40f7-ba57-f5a3252799b1/meskie-buty-do-biegania-w-terenie-zegama-ZdbtbB.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/29a69268-55ec-4414-9dc9-061e17027a6b/meskie-buty-do-biegania-w-terenie-zegama-ZdbtbB.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/bd9d6888-2ecb-4c52-8a5d-0b232b913092/meskie-buty-do-biegania-w-terenie-zegama-ZdbtbB.png",
      ],
    },
  ],
  total: 16,
}))();
